no_cash_valute_list = [
    {'name': 'Bitcoin',
     'code_name': 'BTC',
     'type_valute': 'Криптовалюта'},
    {'name': 'Bitcoin Cash',
     'code_name': 'BCH',
     'type_valute': 'Криптовалюта'},
    {'name': 'Ethereum',
     'code_name': 'ETH',
     'type_valute': 'Криптовалюта'},
    {'name': 'Ethereum Classic',
     'code_name': 'ETC',
     'type_valute': 'Криптовалюта'},
    {'name': 'Litecoin',
     'code_name': 'LTC',
     'type_valute': 'Криптовалюта'},
    {'name': 'Ripple',
     'code_name': 'XRP',
     'type_valute': 'Криптовалюта'},
    {'name': 'Monero',
     'code_name': 'XMR',
     'type_valute': 'Криптовалюта'},
    {'name': 'Dogecoin',
     'code_name': 'DOGE',
     'type_valute': 'Криптовалюта'},
    {'name': 'Dash',
     'code_name': 'DASH',
     'type_valute': 'Криптовалюта'},
    {'name': 'Tether ERC20 USDT',
     'code_name': 'USDTERC20',
     'type_valute': 'Криптовалюта'},
    {'name': 'Tether TRC20 USDT',
     'code_name': 'USDTTRC20',
     'type_valute': 'Криптовалюта'},
    {'name': 'Tether BEP20 USDT',
     'code_name': 'USDTBEP20',
     'type_valute': 'Криптовалюта'},
    {'name': 'TRON',
     'code_name': 'TRX',
     'type_valute': 'Криптовалюта'},
    {'name': 'BinanceCoin BEP20 BNB',
     'code_name': 'BNBBEP20',
     'type_valute': 'Криптовалюта'},
    {'name': 'Solana',
     'code_name': 'SOL',
     'type_valute': 'Криптовалюта'},
    {'name': 'Toncoin',
     'code_name': 'TON',
     'type_valute': 'Криптовалюта'},
    {'name': 'WebMoney',
     'code_name': 'WMZ',
     'type_valute': 'Электронные деньги'},
    {'name': 'Perfect Money USD',
     'code_name': 'PMUSD',
     'type_valute': 'Электронные деньги'},
    {'name': 'ЮMoney RUB',
     'code_name': 'YAMRUB',
     'type_valute': 'Электронные деньги'},
    {'name': 'QIWI RUB',
     'code_name': 'QWRUB',
     'type_valute': 'Электронные деньги'},
    {'name': 'PayPal USD',
     'code_name': 'PPUSD',
     'type_valute': 'Электронные деньги'},
    {'name': 'Advanced Cash USD',
     'code_name': 'ADVCUSD',
     'type_valute': 'Электронные деньги'},
    {'name': 'Advanced Cash RUB',
     'code_name': 'ADVCRUB',
     'type_valute': 'Электронные деньги'},
    {'name': 'Payeer USD',
     'code_name': 'PRUSD',
     'type_valute': 'Электронные деньги'},
    {'name': 'Payeer RUB',
     'code_name': 'PRRUB',
     'type_valute': 'Электронные деньги'},
    {'name': 'Skrill USD',
     'code_name': 'SKLUSD',
     'type_valute': 'Электронные деньги'},
    {'name': 'Exmo USD',
     'code_name': 'EXMUSD',
     'type_valute': 'Балансы криптобирж'},
    {'name': 'Binance RUB',
     'code_name': 'BNACRUB',
     'type_valute': 'Балансы криптобирж'},
    {'name': 'Сбербанк RUB',
     'code_name': 'SBERRUB',
     'type_valute': 'Интернет-банкинг'},
    {'name': 'Альфа-Банк RUB',
     'code_name': 'ACRUB',
     'type_valute': 'Интернет-банкинг'},
    {'name': 'Тинькофф RUB',
     'code_name': 'TCSBRUB',
    'type_valute': 'Интернет-банкинг'},
    {'name': 'ВТБ RUB',
     'code_name': 'TBRUB',
     'type_valute': 'Интернет-банкинг'},
    {'name': 'Приват 24 UAH',
     'code_name': 'P24UAH',
     'type_valute': 'Интернет-банкинг'},
    {'name': 'Kaspi Bank KZT',
     'code_name': 'KSPBKZT',
     'type_valute': 'Интернет-банкинг'},
    {'name': 'Visa/MasterCard USD',
     'code_name': 'CARDUSD',
     'type_valute': 'Интернет-банкинг'},
    {'name': 'Visa/MasterCard RUB',
     'code_name': 'CARDRUB',
     'type_valute': 'Интернет-банкинг'},
    {'name': 'Visa/MasterCard UAH',
     'code_name': 'CARDUAH',
     'type_valute': 'Интернет-банкинг'},
    {'name': 'Visa/MasterCard BYN',
     'code_name': 'CARDBYN',
     'type_valute': 'Интернет-банкинг'},
    {'name': 'Visa/MasterCard KZT',
     'code_name': 'CARDKZT',
     'type_valute': 'Интернет-банкинг'},
    {'name': 'Карта Мир RUB',
     'code_name': 'MIRCRUB',
     'type_valute': 'Интернет-банкинг'},
    {'name': 'WU USD',
     'code_name': 'WUUSD',
     'type_valute': 'Денежные переводы'},
]