services:

  django_fastapi:
    build: .
    environment:
      - POSTGRES_HOST=psql_db
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=1234
      - DJANGO_SUPERUSER_EMAIL=yashenkov.q@gmail.com
    env_file:
      - ./.env
    container_name: django_fastapi
    ports:
      - '8000:8000'
    depends_on:
      - psql_db
      - rabbitmq3
      - celery_worker
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py loaddata valute.json &&
                    python manage.py createsuperuser --no-input &&
                    uvicorn project.asgi:app --host 0.0.0.0"
                    # python manage.py create_rating &&

  rabbitmq3:
    image: rabbitmq:3.6.9
    ports:
    - "5672:5672"
    - "15672:15672"


  celery_worker:
    build: .
    command: sh -c 'celery -A project worker -l info'
    environment:
      - POSTGRES_HOST=psql_db
    env_file:
      - ./.env
    depends_on:
      - rabbitmq3
      - psql_db

  psql_db:
    image: postgres:14
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: