# Generated by Django 4.2.7 on 2023-11-15 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Название обменника')),
                ('xml_url', models.CharField(max_length=50, verbose_name='Сслыка на XML файл')),
                ('partner_link', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Партнёрская ссылка')),
                ('period_for_update', models.IntegerField(verbose_name='Частота обновлений в минутах')),
            ],
            options={
                'verbose_name': 'Обменник',
                'verbose_name_plural': 'Обменники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NoCashValute',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Название валюты')),
                ('code_name', models.CharField(max_length=10, unique=True, verbose_name='Кодовое сокращение')),
                ('type_valute', models.CharField(choices=[('Криптовалюта', 'Криптовалюта'), ('Электронные деньги', 'Электронные деньги'), ('Балансы криптобирж', 'Балансы криптобирж'), ('Интернет-банкинг', 'Интернет-банкинг'), ('Денежные переводы', 'Денежные переводы')], max_length=30, verbose_name='Тип валюты')),
            ],
            options={
                'verbose_name': 'Безналичная валюта',
                'verbose_name_plural': 'Безналичные валюты',
                'ordering': ['type_valute', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('exchange_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rating', models.CharField(default=None, max_length=50, null=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valute_from', models.CharField(max_length=10, verbose_name='Отдаём')),
                ('valute_to', models.CharField(max_length=10, verbose_name='Получаем')),
                ('in_count', models.FloatField(verbose_name='Сколько отдаём')),
                ('out_count', models.FloatField(verbose_name='Сколько получаем')),
                ('min_amount', models.CharField(max_length=50, verbose_name='Минимальное количество')),
                ('max_amount', models.CharField(max_length=50, verbose_name='Максимальное количество')),
                ('exchange_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='api.exchange', verbose_name='Обменник')),
            ],
            options={
                'verbose_name': 'Готовое направление',
                'verbose_name_plural': 'Готовые направления',
                'ordering': ['exchange_name'],
                'unique_together': {('exchange_name', 'valute_from', 'valute_to')},
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valute_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valutes_from', to='api.nocashvalute', to_field='code_name', verbose_name='Отдаём')),
                ('valute_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valutes_to', to='api.nocashvalute', to_field='code_name', verbose_name='Получаем')),
            ],
            options={
                'verbose_name': 'Направление для обмена',
                'verbose_name_plural': 'Направления для обмена',
                'unique_together': {('valute_from', 'valute_to')},
            },
        ),
    ]
