# Generated by Django 4.2.7 on 2023-11-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='period_for_update',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Частота обновлений в минутах'),
        ),
    ]
