# Generated by Django 4.2.7 on 2023-11-14 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_direction_options_alter_exchange_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangedirection',
            options={'ordering': ['exchange_name'], 'verbose_name': 'Готовое направление', 'verbose_name_plural': 'Готовые направления'},
        ),
        migrations.AlterField(
            model_name='direction',
            name='valute_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valutes_from', to='api.nocashvalute', to_field='code_name', verbose_name='Отдаём'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='valute_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valutes_to', to='api.nocashvalute', to_field='code_name', verbose_name='Получаем'),
        ),
        migrations.AlterField(
            model_name='exchangedirection',
            name='exchange_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exchange', verbose_name='Обменник'),
        ),
        migrations.AlterField(
            model_name='exchangedirection',
            name='in_count',
            field=models.FloatField(verbose_name='Сколько отдаём'),
        ),
        migrations.AlterField(
            model_name='exchangedirection',
            name='max_amount',
            field=models.CharField(max_length=50, verbose_name='Максимальное количество'),
        ),
        migrations.AlterField(
            model_name='exchangedirection',
            name='min_amount',
            field=models.CharField(max_length=50, verbose_name='Минимальное количество'),
        ),
        migrations.AlterField(
            model_name='exchangedirection',
            name='out_count',
            field=models.FloatField(verbose_name='Сколько получаем'),
        ),
        migrations.AlterField(
            model_name='exchangedirection',
            name='valute_from',
            field=models.CharField(max_length=10, verbose_name='Отдаём'),
        ),
        migrations.AlterField(
            model_name='exchangedirection',
            name='valute_to',
            field=models.CharField(max_length=10, verbose_name='Получаем'),
        ),
    ]
