# Generated by Django 4.2.7 on 2023-11-16 18:17

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_exchange_period_for_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangedirection',
            options={'ordering': ['exchange_name', 'valute_from'], 'verbose_name': 'Готовое направление', 'verbose_name_plural': 'Готовые направления'},
        ),
        migrations.AlterField(
            model_name='exchange',
            name='period_for_update',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[api.models.is_positive_validate], verbose_name='Частота обновлений в минутах'),
        ),
    ]
