# Generated by Django 4.2.7 on 2023-11-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_direction_exchange_exchangedirection_nocashvalute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nocashvalute',
            name='code_name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nocashvalute',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='nocashvalute',
            name='type_valute',
            field=models.CharField(choices=[('Криптовалюта', 'Криптовалюта'), ('Электронные деньги', 'Электронные деньги'), ('Балансы криптобирж', 'Балансы криптобирж'), ('Интернет-банкинг', 'Интернет-банкинг'), ('Денежные переводы', 'Денежные переводы')], max_length=30),
        ),
    ]
