# Generated by Django 4.2.7 on 2023-11-17 05:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_exchangedirection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='period_for_update',
            field=models.IntegerField(blank=True, default=30, null=True, validators=[api.models.is_positive_validate], verbose_name='Частота обновлений в минутах'),
        ),
    ]
