# Generated by Django 4.2.7 on 2023-11-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_exchangedirection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Название обменника'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='partner_link',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Партнёрская ссылка'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='xml_url',
            field=models.CharField(max_length=50, verbose_name='Сслыка на XML файл'),
        ),
        migrations.AlterField(
            model_name='nocashvalute',
            name='code_name',
            field=models.CharField(max_length=10, unique=True, verbose_name='Кодовое сокращение'),
        ),
        migrations.AlterField(
            model_name='nocashvalute',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Название валюты'),
        ),
        migrations.AlterField(
            model_name='nocashvalute',
            name='type_valute',
            field=models.CharField(choices=[('Криптовалюта', 'Криптовалюта'), ('Электронные деньги', 'Электронные деньги'), ('Балансы криптобирж', 'Балансы криптобирж'), ('Интернет-банкинг', 'Интернет-банкинг'), ('Денежные переводы', 'Денежные переводы')], max_length=30, verbose_name='Тип валюты'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangedirection',
            unique_together={('exchange_name', 'valute_from', 'valute_to')},
        ),
    ]
