# Generated by Django 4.2.7 on 2023-11-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_nocashvalute_code_name_alter_nocashvalute_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nocashvalute',
            name='code_name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='nocashvalute',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
