# Generated by Django 4.2.7 on 2023-11-20 05:32

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_exchange_period_for_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='direction_black_list',
            field=models.ManyToManyField(to='api.direction'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='period_for_update',
            field=models.IntegerField(blank=True, default=30, null=True, validators=[api.models.is_positive_validate], verbose_name='Частота обновлений в секундах'),
        ),
    ]
