# Generated by Django 4.2.7 on 2023-11-10 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_nocashvalute_code_name_alter_nocashvalute_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='valute_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valutes_from', to='api.nocashvalute', to_field='code_name'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='valute_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valutes_to', to='api.nocashvalute', to_field='code_name'),
        ),
    ]
