# Generated by Django 4.2.7 on 2023-11-11 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_exchangedirection_max_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='direction',
            unique_together={('valute_from', 'valute_to')},
        ),
    ]
