# Generated by Django 4.2.7 on 2023-11-11 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_direction_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('exchange_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rating', models.CharField(default=None, max_length=50, null=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exchange')),
            ],
        ),
    ]
