# Generated by Django 4.2.7 on 2023-11-24 06:58

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_direction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangedirection',
            options={'ordering': ['exchange_name', 'valute_from', 'valute_to'], 'verbose_name': 'Готовое направление', 'verbose_name_plural': 'Готовые направления'},
        ),
        migrations.AlterField(
            model_name='exchange',
            name='period_for_update',
            field=models.IntegerField(blank=True, default=60, help_text='Значение - положительное целое число.При установлении в 0, прекращает задачу переодические обновления', null=True, validators=[api.models.is_positive_validate], verbose_name='Частота обновлений в секундах'),
        ),
    ]
