# Generated by Django 4.2.7 on 2023-11-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_exchange_period_for_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус обменника'),
        ),
    ]
