# Generated by Django 4.2.7 on 2023-11-29 04:49

from django.db import migrations, models
import django.db.models.deletion
import no_cash.utils.model_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Направление для обмена',
                'verbose_name_plural': 'Направления для обмена',
                'ordering': ['valute_from', 'valute_to'],
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Название обменника')),
                ('xml_url', models.CharField(max_length=50, verbose_name='Сслыка на XML файл')),
                ('partner_link', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Партнёрская ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус обменника')),
                ('period_for_update', models.IntegerField(blank=True, default=60, help_text='Значение - положительное целое число.При установлении в 0, останавливает задачу переодических обновлений', null=True, validators=[no_cash.utils.model_validators.is_positive_validate], verbose_name='Частота обновлений в секундах')),
                ('direction_black_list', models.ManyToManyField(to='no_cash.direction', verbose_name='Чёрный список')),
            ],
            options={
                'verbose_name': 'Обменник',
                'verbose_name_plural': 'Обменники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NoCashValute',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Название валюты')),
                ('code_name', models.CharField(max_length=10, unique=True, verbose_name='Кодовое сокращение')),
                ('type_valute', models.CharField(choices=[('Криптовалюта', 'Криптовалюта'), ('Электронные деньги', 'Электронные деньги'), ('Балансы криптобирж', 'Балансы криптобирж'), ('Интернет-банкинг', 'Интернет-банкинг'), ('Денежные переводы', 'Денежные переводы')], max_length=30, verbose_name='Тип валюты')),
                ('icon_url', models.FileField(null=True, upload_to='icons/', verbose_name='Иконка валюты')),
            ],
            options={
                'verbose_name': 'Безналичная валюта',
                'verbose_name_plural': 'Безналичные валюты',
                'ordering': ['code_name'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(default=None, max_length=50, null=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='no_cash.exchange')),
            ],
        ),
        migrations.AddField(
            model_name='direction',
            name='valute_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valutes_from', to='no_cash.nocashvalute', to_field='code_name', verbose_name='Отдаём'),
        ),
        migrations.AddField(
            model_name='direction',
            name='valute_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valutes_to', to='no_cash.nocashvalute', to_field='code_name', verbose_name='Получаем'),
        ),
        migrations.CreateModel(
            name='ExchangeDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valute_from', models.CharField(max_length=10, verbose_name='Отдаём')),
                ('valute_to', models.CharField(max_length=10, verbose_name='Получаем')),
                ('in_count', models.FloatField(verbose_name='Сколько отдаём')),
                ('out_count', models.FloatField(verbose_name='Сколько получаем')),
                ('min_amount', models.CharField(max_length=50, verbose_name='Минимальное количество')),
                ('max_amount', models.CharField(max_length=50, verbose_name='Максимальное количество')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='no_cash.exchange', verbose_name='Обменник')),
            ],
            options={
                'verbose_name': 'Готовое направление',
                'verbose_name_plural': 'Готовые направления',
                'ordering': ['exchange', 'valute_from', 'valute_to'],
                'unique_together': {('exchange', 'valute_from', 'valute_to')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='direction',
            unique_together={('valute_from', 'valute_to')},
        ),
    ]
