# Generated by Django 4.2.7 on 2023-12-11 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangedirection',
            options={'ordering': ['-is_active', 'exchange', 'city', 'valute_from', 'valute_to'], 'verbose_name': 'Готовое направление', 'verbose_name_plural': 'Готовые направления'},
        ),
    ]
