# Generated by Django 4.2.7 on 2023-12-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklistelement',
            options={'ordering': ['city', 'valute_from', 'valute_to'], 'verbose_name': 'Элемент чёрного списка', 'verbose_name_plural': 'Элементы чёрного списка'},
        ),
    ]
