# Generated by Django 4.2.7 on 2023-12-05 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_alter_blacklistelement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangedirection',
            options={'ordering': ['exchange', 'city', 'valute_from', 'valute_to'], 'verbose_name': 'Готовое направление', 'verbose_name_plural': 'Готовые направления'},
        ),
    ]
